"""Update field in Menu Model

Revision ID: 0f13957f7bd6
Revises: ceb1db30817b
Create Date: 2021-05-26 21:38:33.122758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f13957f7bd6'
down_revision = 'ceb1db30817b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('name_2', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'name_2')
    # ### end Alembic commands ###
