"""add

Revision ID: 21858235cd8f
Revises: bdc32690983f
Create Date: 2021-06-18 21:31:48.519110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21858235cd8f'
down_revision = 'bdc32690983f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salesType_name'), 'salesType', ['name'], unique=False)
    op.create_table('tax',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_valor'), 'tax', ['valor'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_valor'), table_name='tax')
    op.drop_table('tax')
    op.drop_index(op.f('ix_salesType_name'), table_name='salesType')
    op.drop_table('salesType')
    # ### end Alembic commands ###
