"""Add field to model Menu

Revision ID: 2640aaca1674
Revises: 37bf12ab5220
Create Date: 2021-06-11 19:51:43.443281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2640aaca1674'
down_revision = '37bf12ab5220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('url', sa.String(length=50), nullable=True))
    op.add_column('menu', sa.Column('icon', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'icon')
    op.drop_column('menu', 'url')
    # ### end Alembic commands ###
