"""init sales

Revision ID: 8bdb2b10232f
Revises: d31f21ac6410
Create Date: 2021-06-19 01:24:01.780370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bdb2b10232f'
down_revision = 'd31f21ac6410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tax_id', sa.Integer(), nullable=True),
    sa.Column('salesType_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salesType_id'], ['salesType.id'], ),
    sa.ForeignKeyConstraint(['tax_id'], ['tax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
