"""Add rol_id field to UserModel

Revision ID: b3af6d8346b7
Revises: d19b5f43e9b5
Create Date: 2021-06-12 11:10:31.192588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3af6d8346b7'
down_revision = 'd19b5f43e9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rol_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rol_id')
    # ### end Alembic commands ###
