"""Add User Model

Revision ID: c15681da044f
Revises: 0f13957f7bd6
Create Date: 2021-06-01 21:03:33.718844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15681da044f'
down_revision = '0f13957f7bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_column('menu', 'name_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('name_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('users')
    # ### end Alembic commands ###
